/**:
  # Global Parameters
  ros__parameters:
    use_sim_time: True
    tf_timeout_threshold: 0.0

/**:
  # Basic Robotics Functions
  platform:
    ros__parameters:
      cmd_freq: 100.0  # Hz of platform commands send

  # State Estimator
  state_estimator:
    ros__parameters:
      use_gazebo_tf: true
      plugin_name: "ground_truth"

  # Motion Controller
  controller_manager:
    ros__parameters:
      cmd_freq: 100.0 # Hz of controller commands send
      use_bypass: false
      plugin_name: "differential_flatness_controller"

  # Behaviors Motion
  TakeoffBehavior:
    ros__parameters:
      takeoff_plugin_name: "takeoff_plugin_trajectory"
  LandBehavior:
    ros__parameters:
      land_plugin_name: "land_plugin_trajectory"
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: "go_to_plugin_trajectory"
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: "follow_path_plugin_trajectory"

drone0:
  # Motion Controller
  controller_manager:
    ros__parameters:
      # Differential Flatness Controller
      mass: 0.853
      trajectory_control:
        antiwindup_cte: 1.0
        alpha: 0.1
        kp:
          x: 2.35
          y: 2.35
          z: 2.35
        ki:
          x: 0.0
          y: 0.0
          z: 0.0
        kd:
          x: 2.65
          y: 2.65
          z: 2.65
        roll_control:
          kp: 3.35
        pitch_control:
          kp: 3.35
        yaw_control:
          kp: 3.35

        # kp:
        #   x: 3.15
        #   y: 3.15
        #   z: 3.15
        # ki:
        #   x: 0.75
        #   y: 0.75
        #   z: 0.75
        # kd:
        #   x: 1.985
        #   y: 1.985
        #   z: 1.985
        # roll_control:
        #   kp: 3.85
        # pitch_control:
        #   kp: 3.85
        # yaw_control:
        #   kp: 3.85