world_name: "empty"
drones:
  - model_type: "zmr250"
    model_name: "drone0"
    flight_time: 60
    xyz:
      - 0.0
      - 0.0
      - 0.1
    enable_velocity_control: false 
    enable_acro_control: true
