/**:
  # Global Parameters
  ros__parameters:
    tf_timeout_threshold: 0.0

/**:
  # Basic Robotics Functions
  # Platform
  platform:
    ros__parameters:
      cmd_freq: 100.0  # Hz of platform commands send
      info_freq: 10.0  # Hz of platform info publish
      device: "/dev/ttyTHS1"  # Serial port to connect to the Platform
      baudrate: 115200 # Baudrate of the serial port
      imu_hz: 0.00625
      battery_hz: 0.2
      thrust:
        max : 44.0  # Max thrust to send to platform (N)
        min : 0.15  # Min thrust to send to platform (N)
      roll_rate:
        max : 360.0 # Max roll rate to send to platform (deg/s) # ATTENTION: this is in deg/s
        min : -360.0 # Min roll rate to send to platform (deg/s) # ATTENTION: this is in deg/s
      pitch_rate:
        max : 360.0  # Max pitch rate to send to platform (deg/s) # ATTENTION: this is in deg/s
        min : -360.0  # Min pitch rate to send to platform (deg/s) # ATTENTION: this is in deg/s
      yaw_rate:
        max : 360.0  # Max yaw rate to send to platform (deg/s) # ATTENTION: this is in deg/s
        min : -360.0  # Min yaw rate to send to platform (deg/s) # ATTENTION: this is in deg/s
      use_thrust_map: true # Flag to use thrust map
      thrust_map:
        a: 2891.7649649665987
        b: 115.68304893912368
        c: -136.6433473374485
        d: -2.7940080155124005
        e: -0.7629228407317176
        f: 2.4731771341179454

      limit_output: true  # Flag to limit the output of the platform
      limit_roll_percent: 1.0  # Limit of roll command in percent (between 0 and 1)
      limit_pitch_percent: 1.0  # Limit of pitch command in percent (between 0 and 1)
      limit_yaw_percent: 1.0  # Limit of yaw command in percent (between 0 and 1)
      limit_thrust_percent: 1.0  # Limit of thrust command in percent (between 0 and 1)
  
  # Controller Manager
  controller_manager:
    ros__parameters:
      cmd_freq: 100.0 # Hz of controller commands send
      use_bypass: false
      # Differential Flatness Controller
      plugin_name: "differential_flatness_controller"
      mass: 0.862
      trajectory_control:
        antiwindup_cte: 1.0
        alpha: 0.1
        kp:
          x: 3.5
          y: 3.5
          z: 4.0
        ki:
          x: 0.01
          y: 0.01
          z: 0.05
        kd:
          x: 1.6
          y: 1.6
          z: 2.1
        roll_control:
          kp: 6.0
        pitch_control:
          kp: 6.0
        yaw_control:
          kp: 1.3

  # State Estimator
  state_estimator:
    ros__parameters:
      # # Motion Capture
      # plugin_name: "mocap_pose"
      # mocap_topic: "/mocap/rigid_bodies"
      # twist_smooth_filter_cte: 0.05
      # orientation_smooth_filter_cte: 0.1

      # Ground Truth
      plugin_name: "ground_truth"

  # Behaviors Motion
  TakeoffBehavior:
    ros__parameters:
      takeoff_plugin_name: "takeoff_plugin_trajectory"
  LandBehavior:
    ros__parameters:
      land_plugin_name: "land_plugin_trajectory"
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: "go_to_plugin_trajectory"
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: "follow_path_plugin_trajectory"
  TrajectoryGeneratorBehavior:
    ros__parameters:
      run_frequency: 100.0 # Frequency of the behavior
      # sampling_n: 101 # Number of sampling of the trajectory
      # sampling_dt: 0.005 # Time between each sampling

  # Hardware Interfaces
  usb_camera_interface:
    ros__parameters:
      # Package configuration
      arducam: true
      device: "0" # Id of camera device
      # device: "/dev/video0" # Path to the camera device
      framerate: 60.0 # Frame rate of the camera (fps)
      encoding: "bgr8" # Image encoding
      # Camera configuration
      camera_transform:
        parent_frame: "base_link" # Parent frame of the camera
        x: 0.11 # Translation in x (m)
        y: 0.0 # Translation in y (m)
        z: 0.025 # Translation in z (m)
        roll: -1.57079632679 # Rotation around x (rad)
        pitch: 0.0 # Rotation around y (rad)
        yaw: -1.57079632679 # Rotation around z (rad)

# drone0:
#   # Platform
#   # mavros/mavros_node:
#   #   ros__parameters:
#   #     fcu_url: "/dev/ttyACM0:57600" # Autopilot address for connection
#   #     #fcu_url: "/dev/ttyUSB0:115200" # Autopilot address for connection
#   #     tgt_system: 1 # Target system ID = Instance + 1
#   state_estimator:
#     ros__parameters:
#       rigid_body_name: "33"
