/**:
  # Global Parameters
  ros__parameters:
    use_sim_time: true
    tf_timeout_threshold: 0.0

/**:
  # Basic Robotics Functions
  platform:
    ros__parameters:
      cmd_freq: 100.0  # Hz of platform commands send
      enable_takeoff_platform: true  # Enable takeoff platform, only for debugging purposes
      enable_land_platform: true  # Enable land platform, only for debugging purposes

  # State Estimator
  state_estimator:
    ros__parameters:
      use_gazebo_tf: true
      plugin_name: "ground_truth"
      # Outdoor (GPS)
      use_gps: true
      set_origin_on_start: true # Set origin on start

  # Motion Controller
  controller_manager:
    ros__parameters:
      cmd_freq: 100.0 # Hz of controller commands send
      use_bypass: false
      plugin_name: "pid_speed_controller"

  # Behaviors Motion
  TakeoffBehavior:
    ros__parameters:
      takeoff_plugin_name: "takeoff_plugin_platform"
  LandBehavior:
    ros__parameters:
      land_plugin_name: "land_plugin_platform"
  GoToBehavior:
    ros__parameters:
      go_to_plugin_name: "go_to_plugin_position"
  FollowPathBehavior:
    ros__parameters:
      follow_path_plugin_name: "follow_path_plugin_position"
  FollowReferenceBehavior:
    ros__parameters:
      follow_reference_max_speed_x: 10.0 # Maximum speed in x direction
      follow_reference_max_speed_y: 10.0 # Maximum speed in y direction
      follow_reference_max_speed_z: 10.0 # Maximum speed in z direction

drone0:
  # Motion Controller
  controller_manager:
    ros__parameters:
      # PID Controller
      proportional_limitation: true
      position_control:
        reset_integral: false
        antiwindup_cte: 0.5
        alpha: 0.2
        kp:
          x: 1.5
          y: 1.5
          z: 1.5
        kd:
          x: 0.0
          y: 0.0
          z: 0.0
        ki:
          x: 0.5
          y: 0.5
          z: 0.5
      trajectory_control:
        reset_integral: false
        antiwindup_cte : 1.0
        alpha: 0.3
        kp:
          x: 0.4
          y: 0.4
          z: 0.4
        kd:
          x: 0.0001
          y: 0.0001
          z: 0.0001
        ki:
          x: 0.0
          y: 0.0
          z: 0.0
      yaw_control:
        reset_integral: false
        antiwindup_cte : 1.0
        alpha: 0.3
        kp: 1.0
        kd: 0.001
        ki: 0.0
