/**:
  ros__parameters:
    controller_manager:
      ros__parameters:
        cmd_freq: 100.0 # Hz of controller commands send
        use_bypass: false
        # Differential Flatness Controller
        mass: 1.03
        trajectory_control:
          antiwindup_cte: 1.0
          alpha: 0.1
          kp:
            x: 2.65
            y: 2.65
            z: 2.65
          ki:
            x: 0.15
            y: 0.15
            z: 0.15
          kd:
            x: 1.35
            y: 1.35
            z: 1.35
          roll_control:
            kp: 5.5
          pitch_control:
            kp: 5.5
          yaw_control:
            kp: 5.5